version: '3.3'
services:
  oraclixwebsitedev:
    container_name: oraclixWebsiteDev
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm run developmentNodemon
    ports:
      - "3007:3007"
