version: '3.3'
services:
  zorahwebsite:
    container_name: zorahWebsite
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm run production
    ports:
      - "3007:3007"
